
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";


import {SocketProvider} from "../context/SocketProvider"
import { Socket } from "socket.io-client";
import { Providers } from "./providers";
import { ThemeProvider } from "./theme-provider";
const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    
      <html lang="en">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Providers>
        <SocketProvider>
        <body className={font.className}>{children}</body>
        </SocketProvider>
        </Providers>
        </ThemeProvider>
      </html>
    
   
  );
}
